default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-recipes-final-project_development


test:
  <<: *default
  database: rails-recipes-final-project_test
